// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OwnerCarService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OwnerCarService.Models.Car", b =>
                {
                    b.Property<int>("CarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CarID"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Deposit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("FuelConsumption")
                        .HasColumnType("double");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("InspectionExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("InsuranceExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<string>("NameCar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OwnerCarID")
                        .HasColumnType("int");

                    b.Property<string>("OwnershipDocumentNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegistrationPlace")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Seat")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeCar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.PrimitiveCollection<string>("imageUrls")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CarID");

                    b.HasIndex("OwnerCarID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("OwnerCarService.Models.Maintenance", b =>
                {
                    b.Property<int>("MaintenanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaintenanceID"));

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MaintenanceID");

                    b.HasIndex("CarID");

                    b.ToTable("Maintenances");
                });

            modelBuilder.Entity("OwnerCarService.Models.OwnerCar", b =>
                {
                    b.Property<int>("OwnerCarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OwnerCarId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DrivingLicence")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LicenceExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LicenceIssueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("OwnerCarId");

                    b.ToTable("OwnerCars");
                });

            modelBuilder.Entity("OwnerCarService.Models.Car", b =>
                {
                    b.HasOne("OwnerCarService.Models.OwnerCar", "OwnerCar")
                        .WithMany("Cars")
                        .HasForeignKey("OwnerCarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerCar");
                });

            modelBuilder.Entity("OwnerCarService.Models.Maintenance", b =>
                {
                    b.HasOne("OwnerCarService.Models.Car", "Car")
                        .WithMany("Maintenances")
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("OwnerCarService.Models.Car", b =>
                {
                    b.Navigation("Maintenances");
                });

            modelBuilder.Entity("OwnerCarService.Models.OwnerCar", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
