-- Create databases
CREATE DATABASE IF NOT EXISTS OwnerCarDB;
CREATE DATABASE IF NOT EXISTS TelemetryDB;
CREATE DATABASE IF NOT EXISTS AuthDB;
CREATE DATABASE IF NOT EXISTS AdminDB;
CREATE DATABASE IF NOT EXISTS NotificationDB;

-- Grant permissions
GRANT ALL PRIVILEGES ON OwnerCarDB.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON TelemetryDB.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON AuthDB.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON AdminDB.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON NotificationDB.* TO 'root'@'%';

FLUSH PRIVILEGES;
