// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OwnerCarConsumer;

#nullable disable

namespace OwnerCarConsumer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104163454_ni")]
    partial class ni
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OwnerCarConsumer.Models.CarLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "carID");

                    b.Property<double>("Latitude")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "longitude");

                    b.Property<double>("Speed")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "speed");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("CarLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
