FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ./Server/AdminService/. .
RUN dotnet nuget locals all --clear
RUN dotnet tool install --global dotnet-ef --version 8.0.0 --add-source https://api.nuget.org/v3/index.json
ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet restore /src/SDCRMS.AdminService.csproj
RUN dotnet build -c Release /src/SDCRMS.AdminService.csproj

CMD ["dotnet", "ef", "database", "update"]
